version: '3.7'

services:
  docker-api-swagger:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-api-swagger
    container_name: docker-api-swagger
    restart: always
    ports:
      - 8083:80
    environment:
      - DOCKER_SERVER=10.1.0.41
      - DOCKER_PORT=2375
