version: '3.8'

services:
  docker-api-swagger:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-api-swagger
    container_name: docker-api-swagger
    hostname: docker-api-swagger
    restart: always
    ports:
      - 8083:8083
    environment:
      - DOCKER_SERVER=192.168.88.18
      - DOCKER_PORT=2376
